// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickVote.Models;

#nullable disable

namespace QuickVote.Migrations
{
    [DbContext(typeof(QuickVoteContext))]
    [Migration("20260627182714_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("QuickVote.Models.Answer", b =>
                {
                    b.Property<string>("AnswerID")
                        .HasColumnType("TEXT");

                    b.Property<int>("OptionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PollID")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoterName")
                        .HasColumnType("TEXT");

                    b.HasKey("AnswerID");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("QuickVote.Models.Poll", b =>
                {
                    b.Property<string>("PollID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT");

                    b.HasKey("PollID");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("QuickVote.Models.PollOption", b =>
                {
                    b.Property<int>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("PollID")
                        .HasColumnType("TEXT");

                    b.HasKey("OptionID");

                    b.ToTable("PollOption");
                });
#pragma warning restore 612, 618
        }
    }
}
