// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickVote.Data;

#nullable disable

namespace QuickVote.Migrations
{
    [DbContext(typeof(QuickVoteContext))]
    [Migration("20260625140137_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("QuickVote.Models.Poll", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("CollectedAnswersIDs")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Options")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Poll");
                });
#pragma warning restore 612, 618
        }
    }
}
