@QuickVote_HostAddress = https://localhost:7269

GET {{QuickVote_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{QuickVote_HostAddress}}/polls
Content-Type: application/json

{
	"Poll":{
			"Question":"Where are we going 2",
			"EndDate" : "2026-06-30T00:00:00"
	},
  "Options": [{  
			"Description": "North"
		},
  {  
			"Description": "South"
		},
  {  
			"Description": "East"
		},
  {  
			"Description": "West"
		}]  
}

###


GET {{QuickVote_HostAddress}}/polls/
Accept: application/json

###

GET {{QuickVote_HostAddress}}/polls/265f7164-51ea-45fd-a2e0-8bdb8a27f994
Accept: application/json

###

DELETE {{QuickVote_HostAddress}}/polls/66e5c73c-e186-4660-9edf-b1421de347b7
Accept: application/json

###
